[default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 16 # move back to 256+ after full migration of tests
remappings = [
    'ds-test/=lib/ds-test/src/',
    '@yearnvaults/=lib/yearn-vaults/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
